### ISSUE TITLE
Why not using cdn?

### ISSUE THREAD

**Issue by jjangga0214** [hasura/cli-plugins-index#29]
https://github.com/hasura/cli-plugins-index/blob/2392ecd63d445a40df947110bcb5e67ab6b80fea/plugins/cli-ext/v1.3.0/manifest.yaml#L7

I live in Seoul, Korea, and the download speed is very slow. 

Today `hasura plugins install cli-ext` consumes almost 5 minutes for downloading a 20 MB file.
(I feel it's slower than usual, but not sure.)

I don't think it's due to my network or ISP, but just GitHub's server is too far and the middle network between is congested.

Thus I want to suggest cdn for static file serving.

If it's possible, maybe the cli itself (e.g. `cli-hasura-linux-amd64`) could be served through cdn as well.

Thanks.

**Comment by scriptonist** [comment]
@jjangga0214 This should be fixed in the latest releases, `cli-ext` is no longer treated as a plugin.
