### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by jesselve** [hasura/cli-plugins-index#55]
I was able to build a version of the cli-ext plugin for linux on the ARM architecture but am unable to install this plugin using the hasura CLI.  Since it is possible to run the Hasura GraphQL engine and also the Hasura CLI on linux/ARM, the only remaining item for full ARM support is the cli-ext plugin.

Would you be open to a pull request to add ARM architecture support?

Alternatively, is there a way to install the cli-ext plugin without it being added to this index?

For reference, here are the steps that I used to build a version of the cli-ext plugin for linxu/ARM:

```
git clone https://github.com/hasura/graphql-engine.git
cd graphql-engine/cli-ext

# remove lock file to prevent hang:
rm package-lock.json

# install missing pkg package:
npm install pkg --save-dev

# retrieve node12 ARM binaries:
mkdir ~/.pkg-cache/v2.6
wget \
    https://github.com/yao-pkg/pkg-binaries/releases/download/v1.0.0/fetched-v12.18.1-linux-arm64 \
    -O \
    ~/.pkg-cache/v2.6/fetched-v12.18.1-linux-armv6

# build cli-ext for node12-linux-armv6:
npx pkg ./build/command.js --output ./bin/cli-ext-hasura -t node12-linux-armv6
```

**Comment by scriptonist** [comment]
https://github.com/hasura/graphql-engine/issues/6433#issuecomment-881201925
